project:
  type: website

website:
  title: "G Argueta"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - studies.qmd
      - data_topics.qmd
      - words_action.qmd
      - cv.qmd
      - assignments.qmd
      

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

