---
title: "Data Topics"
---

### **Time Series Data and Break Point Analysis**

Areas of research concerned with change should consider time, and effects of the past, as potentially important variables. Cross-sectional studies take measurements from a single point in time, while longitudinal studies take measurements in multiple waves over time. Reference to longitudinal data is common, but here the term longitudinal only is attributable to studies or research designs. Within a longitudinal design, there are repeated measurement and time series data. Repeat measurement is when measurements are taken over many waves but may not be collected at standard time intervals. Time series data are collected on regular intervals and should contain at least thirty measurements. Panel data may be repeated measurement or time series. The key feature of panel data is the measurement of the same entities over time, rather than collecting measurements from the same population even if the entities measured differ.

There are no universal rules or definitions for distinguishing between the terms longitudinal, time series, and panel with regard to study or data types, but these are the definitions used to guide the discussion on this site.

Planned interventions with study groups in comparison to control groups that do not receive an intervention are a common method used for testing hypotheses in longitudinal studies. Break point analysis is a method used to identify unintended or natural interventions that cause change in situations that were not designed or controlled. Break point analysis can also assist in identifying or verifying true changes when compared with stated beliefs about the drivers of change. Knowing the timing of change ensures that perceived drivers are temporally plausible.

### 
